#! /usr/bin/env bash

# create symbolic links to point to git-maintained configuration files

baseFolder=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
myLinker='ln -vsf -T '

cd $HOME

echo 'Linking configuration files under $HOME'
${myLinker} ${baseFolder}/bash_profile .bash_profile
${myLinker} ${baseFolder}/bashrc .bashrc
${myLinker} ${baseFolder}/bash_logout .bash_logout
${myLinker} ${baseFolder}/dircolors .dircolors
${myLinker} ${baseFolder}/inputrc .inputrc
${myLinker} ${baseFolder}/psqlrc .psqlrc
${myLinker} ${baseFolder}/Xresources .Xresources
${myLinker} ${baseFolder}/xprofile .xprofile
${myLinker} ${baseFolder}/gitconfig .gitconfig
${myLinker} ${baseFolder}/npmrc .npmrc

# Don't erase ~/.pgpass if there's one already
if [[ ! -e .pgpass ]]; then
  cp ${baseFolder}/pgpass ~/.pgpass
fi

if [[ ! -d .config ]]; then
  mkdir .config
fi

echo 'Linking configuration files under $HOME/.config'
${myLinker} ${baseFolder}/git ${HOME}/.config/git
${myLinker} ${baseFolder}/mc ${HOME}/.config/mc
${myLinker} ${baseFolder}/kitty ${HOME}/.config/kitty

echo "Install i3 configuration? (y/N)"
read answer
if [[ 'y' = ${answer} ]]; then
  i3Folder="${HOME}/.i3"
  if [[ ! -d ${i3Folder} ]]; then
    mkdir ${i3Folder}
  fi
  cd ${i3Folder}
  ${myLinker} ${baseFolder}/i3/config ${i3Folder}/config
  ${myLinker} ${baseFolder}/i3/status.conf ${i3Folder}/status.conf
fi

# Finally, write down configuration folder path so it can be used by
# ~/.bashrc

echo ${baseFolder} >| ${HOME}/.envFolder
