# This file is called when bash is invoked as an interactive non login
# shell and from remote logins. But it's being sourced from
# ~/.bash_profile to keep all configuration in one place
[[ -r /etc/profile ]] && source /etc/profile

# ~/.envFolder is generated on installation
read baseFolder < ~/.envFolder

commonFolder="${baseFolder}/src/common"
localFolder="${baseFolder}/src/$HOSTNAME"
# ensure local folder exists on new machines
test -d ${localFolder} || mkdir -p ${localFolder}
completionsFolder="${baseFolder}/completions"

# Start only one ssh-agent or use the one already started by the system
source ${commonFolder}/ssh.agent.sh;

# load all that's common to any shell, any machine
for file in `/usr/bin/env ls -1 ${commonFolder}`; do
  source ${commonFolder}/${file};
done

# after ssh agent is running and variables exported...
# source local configurations
for file in `/usr/bin/env ls -1 ${localFolder}`; do
  source ${localFolder}/${file};
done

# source completions
# global
[[ $BASH_COMPLETION = '' ]]\
  && [[ -r /etc/bash_completion ]]\
  && source /etc/bash_completion

# local
for file in `env ls ${completionsFolder}`; do
	source ${completionsFolder}/${file};
done

