# This file is called when bash is invoked as an interactive non login
# shell and from remote logins. But it's being sourced from
# ~/.bash_profile to keep all configuration in one place
[[ -r /etc/profile ]] && source /etc/profile

# ~/.envFolder is generated on installation
read baseFolder < ~/.envFolder

common="${baseFolder}/src/common/*.sh"
thisHostScriptsFolder="${baseFolder}/src/$HOSTNAME"
thisHost="${thisHostScriptsFolder}/*.sh"
# ensure thisHost folder exists on new machines
test -d ${thisHostScriptsFolder} || mkdir -p ${thisHostScriptsFolder}
completions="${baseFolder}/completions"

# load all that's common to any shell, any machine
for file in `/usr/bin/env ls -1 ${common}`; do
  source ${file};
done

# after ssh agent is running and variables exported...
# source thisHost configurations
for file in `/usr/bin/env ls -1 ${thisHost}`; do
  source ${file};
done

# source completions
# global
[[ $BASH_COMPLETION = '' ]]\
  && [[ -r /etc/bash_completion ]]\
  && source /etc/bash_completion

# thisHost
for file in `/usr/bin/env ls -1 ${completions}`; do
  source ${completions}/${file};
done
