# this file is called when bash is invoked as a login shell
# also this is called by:
# - wezterm
# - login shells (bash -l, ssh)

[[ -r "$HOME/.profile" ]] && source "$HOME/.profile"
[[ -r "$HOME/.bashrc" ]] && source "$HOME/.bashrc"
