# This file is called when bash is invoked as an interactive non login
# shell. Ensure it doesn't output anything

# Note: urxvt loads this file instead of ~/.bash_profile

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# ~/.envFolder is generated on installation
read baseFolder < ~/.envFolder

autoload="${baseFolder}/src/autoload/*.sh"
thisHostScriptsFolder="${baseFolder}/src/$HOSTNAME"
thisHost="${thisHostScriptsFolder}/*.sh"
# ensure thisHost folder exists on new machines
test -d ${thisHostScriptsFolder} || mkdir -p ${thisHostScriptsFolder}
completions="${baseFolder}/completions"

# automatically load what's in 'autoload'
for file in `/usr/bin/env ls -1 ${autoload}`; do
  source ${file};
done

# after ssh agent is running and variables exported...
# source thisHost configurations
for file in `/usr/bin/env ls -1 ${thisHost}`; do
  source ${file};
done

# source completions
# global
[[ $BASH_COMPLETION = '' ]]\
  && [[ -r /etc/bash_completion ]]\
  && source /etc/bash_completion

# thisHost
for file in `/usr/bin/env ls -1 ${completions}`; do
  source ${completions}/${file};
done
