-- Environment variables and ecosystem settings.
-- Migrated from Omarchy's default hypr/envs.conf plus local NVIDIA envs.

local function set_env(name, value)
  if name and name ~= "" and value then
    hl.env(name, value)
  end
end

local function load_hyprlang_env_file(path)
  local file = io.open(path, "r")
  if not file then
    return
  end

  for line in file:lines() do
    local name, value = line:match("^%s*env%s*=%s*([^,]+)%s*,%s*(.-)%s*$")
    if name and value then
      set_env(name:match("^%s*(.-)%s*$"), value:match("^%s*(.-)%s*$"))
    end
  end

  file:close()
end

local home = os.getenv("HOME") or ""

-- GUM environment variables for styling purposes, generated by the active
-- Omarchy theme.
load_hyprlang_env_file(home .. "/.config/omarchy/current/theme/gum.env.conf")

-- Cursor size.
set_env("XCURSOR_SIZE", "24")
set_env("HYPRCURSOR_SIZE", "24")

-- Force all apps to use Wayland where possible.
set_env("GDK_BACKEND", "wayland,x11,*")
set_env("QT_QPA_PLATFORM", "wayland;xcb")
set_env("QT_STYLE_OVERRIDE", "kvantum")
set_env("MOZ_ENABLE_WAYLAND", "1")
set_env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
set_env("OZONE_PLATFORM", "wayland")
set_env("XDG_SESSION_TYPE", "wayland")

-- Allow better support for screen sharing (Google Meet, Discord, etc).
set_env("XDG_CURRENT_DESKTOP", "Hyprland")
set_env("XDG_SESSION_DESKTOP", "Hyprland")

-- Use XCompose file.
set_env("XCOMPOSEFILE", home .. "/.XCompose")

-- Local NVIDIA (Turing+ with GSP firmware) envs.
set_env("NVD_BACKEND", "direct")
set_env("LIBVA_DRIVER_NAME", "nvidia")
set_env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

hl.config({
  xwayland = {
    force_zero_scaling = true,
  },
  ecosystem = {
    no_update_news = true,
  },
})
