# Change the default Omarchy look'n'feel

general {
    layout = hy3
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
}

plugin {
  hy3 {
    # Auto-create a tab group for the first window on each workspace
    tab_first_window = true

    tabs {
      height = 22
      padding = 6
      from_top = false
      radius = 6
      border_width = 2
      render_text = true
      text_center = true
      text_font = Sans
      text_height = 8
      text_padding = 3
      blur = true
      opacity = 1.0
    }
  }
}
